@BASE_URL=http://127.0.0.1:8000
@ACCESS_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwOTI5MTg4LCJpYXQiOjE3NTA5Mjg4ODgsImp0aSI6ImY3ZDY3ZTE1Mzg2OTRiZGJiYjhhYjdmMDEwOGZiMWFkIiwidXNlcl9pZCI6MX0.0lOYCq8cjbX94u8DhiCXBznzR6qxn7c30iiyfuIwEr8

###
POST {{BASE_URL}}/api/token/
Content-Type: application/json

{
    "username": "administrator",
    "password": "admin"
}

### 
GET {{BASE_URL}}/api/v1/profiles/
Accept: application/json
Authorization: Bearer {{ACCESS_TOKEN}}