# Generated by Django 5.1.6 on 2025-05-25 11:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_industry_organization_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(default='unknown', max_length=75)),
                ('national_name', models.CharField(default='unknown', max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='established_year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Established year'),
        ),
        migrations.AddField(
            model_name='organization',
            name='local_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Local name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='on_primary_color',
            field=models.CharField(default='000000', max_length=25, verbose_name='on primary color'),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_color',
            field=models.CharField(default='000000', max_length=25, verbose_name='Primary color'),
        ),
    ]
