# Generated by Django 5.2.3 on 2025-08-03 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['user', 'organization'], name='organizatio_user_id_344689_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active', 'is_deleted'], name='organizatio_is_acti_72a67a_idx'),
        ),
    ]
