# Generated by Django 5.2.3 on 2025-08-11 14:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_employee_organizatio_user_id_344689_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industry',
            old_name='self_data',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='industry',
        ),
        migrations.AddField(
            model_name='founder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='founder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='founders',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='organization.founder', verbose_name='Founders'),
        ),
        migrations.AddField(
            model_name='organization',
            name='industries',
            field=models.ManyToManyField(blank=True, to='organization.industry'),
        ),
    ]
