# Generated by Django 5.2.5 on 2025-09-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admanager',
            name='target_url',
            field=models.URLField(blank=True, default='', help_text='URL to navigate to on click', max_length=500, null=True),
        ),
    ]
