# Generated by Django 5.2.5 on 2025-09-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_admanager_target_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='admanager',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Short description'),
        ),
    ]
