# Generated by Django 5.2.7 on 2025-10-26 10:51

from decimal import Decimal

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventticket",
            name="benefits",
        ),
        migrations.RemoveField(
            model_name="eventticket",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="eventticket",
            name="quantity_available",
        ),
        migrations.AddField(
            model_name="eventticket",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventticket",
            name="max_per_order",
            field=models.IntegerField(
                default=10,
                help_text="Maximum tickets per order",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="eventticket",
            name="quantity",
            field=models.IntegerField(
                default=100,
                help_text="Total number of tickets available",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("sold-out", "Sold Out"),
                    ("expired", "Expired"),
                    ("inactive", "Inactive"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="eventticket",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="eventticket",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Ticket name"),
        ),
        migrations.AlterField(
            model_name="eventticket",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="eventticket",
            name="quantity_sold",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="eventticket",
            name="sale_end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Sale end date"
            ),
        ),
        migrations.AlterField(
            model_name="eventticket",
            name="sale_start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Sale start date"
            ),
        ),
    ]
