# Generated by Django 5.0.7 on 2024-11-15 19:11

import django.db.models.deletion
import schools.models.schoolsModel
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('url', models.URLField(blank=True, help_text='Base URL of the platform')),
                ('icon', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=schools.models.schoolsModel.school_logo_upload_path)),
                ('name', models.CharField(blank=True, max_length=75)),
                ('local_name', models.CharField(blank=True, max_length=128, verbose_name='local name')),
                ('short_name', models.CharField(blank=True, max_length=25, verbose_name='short name')),
                ('code', models.CharField(blank=True, max_length=15)),
                ('description', models.TextField(blank=True, default='The school description')),
                ('established', models.DateField(blank=True, null=True)),
                ('founder', models.CharField(blank=True, max_length=125)),
                ('president', models.CharField(blank=True, max_length=125)),
                ('endowment', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'school',
                'verbose_name_plural': 'schools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(db_index=True, max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='Description about the school type')),
                ('icon', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name': 'School Type',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='PlatformProfile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_url', models.URLField(help_text="URL of the school's profile on the platform")),
                ('username', models.CharField(blank=True, help_text='Username or handle on the platform', max_length=128)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='schools.platform')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_profiles', to='schools.school')),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='schools', to='schools.schooltype'),
        ),
        migrations.AddConstraint(
            model_name='platformprofile',
            constraint=models.UniqueConstraint(fields=('school', 'platform'), name='unique_school_platform'),
        ),
    ]
