# Generated by Django 5.0.7 on 2024-12-14 06:25

import schools.models.schoolsModel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=schools.models.schoolsModel.school_cover_image_upload_path, verbose_name='photo'),
        ),
    ]
