# Generated by Django 5.0.7 on 2024-11-23 08:19

import schools.models.schoolsModel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_platform_id_platformprofile_id_school_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='motto',
            field=models.CharField(blank=True, default=None, max_length=250, verbose_name='motto'),
        ),
        migrations.AddField(
            model_name='school',
            name='tuition',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, verbose_name='tuition'),
        ),
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(blank=True, max_length=15, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='school',
            name='endowment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, verbose_name='locations'),
        ),
        migrations.AlterField(
            model_name='school',
            name='established',
            field=models.DateField(blank=True, null=True, verbose_name='established'),
        ),
        migrations.AlterField(
            model_name='school',
            name='founder',
            field=models.CharField(blank=True, max_length=125, verbose_name='founder'),
        ),
        migrations.AlterField(
            model_name='school',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=schools.models.schoolsModel.school_logo_upload_path, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(blank=True, max_length=75, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='school',
            name='president',
            field=models.CharField(blank=True, max_length=125, verbose_name='president'),
        ),
    ]
