# Generated by Django 5.1.6 on 2025-02-14 14:37

import schools.models.schoolsModel
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='unique identifier'),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('street', 'city', 'state', 'zip_code', 'country')},
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('local_name', models.CharField(blank=True, max_length=128)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
                'unique_together': {('name', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Scholarship Slug')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=schools.models.schoolsModel.scholarship_thumbnail_upload_path, verbose_name='thumbnail')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Scholarship Name')),
                ('local_name', models.CharField(blank=True, max_length=255, verbose_name='Scholarship Local Name')),
                ('description', models.TextField(blank=True, verbose_name='Scholarship Description')),
                ('local_description', models.TextField(blank=True, verbose_name='Scholarship Local Description')),
                ('provider', models.CharField(blank=True, max_length=255, verbose_name='Scholarship Provider')),
                ('website', models.URLField(blank=True, verbose_name='Application Website')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Scholarship Amount')),
                ('full_tuition_coverage', models.BooleanField(default=False, verbose_name='Full Tuition Coverage')),
                ('stipend', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monthly Stipend')),
                ('eligibility_criteria', models.TextField(blank=True, verbose_name='Eligibility Criteria')),
                ('min_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Minimum GPA Requirement')),
                ('required_documents', models.TextField(blank=True, verbose_name='Required Documents')),
                ('application_deadline', models.DateField(blank=True, null=True, verbose_name='Application Deadline')),
                ('application_open_date', models.DateField(blank=True, null=True, verbose_name='Application Open Date')),
                ('application_status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Upcoming', 'Upcoming')], default='Upcoming', max_length=50, verbose_name='Application Status')),
                ('renewable', models.BooleanField(default=False, verbose_name='Is Renewable?')),
                ('duration', models.CharField(blank=True, max_length=255, verbose_name='Duration of Scholarship')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('target_countries', models.ManyToManyField(blank=True, to='schools.country', verbose_name='Eligible Countries')),
                ('target_fields', models.ManyToManyField(blank=True, to='schools.fieldofstudy', verbose_name='Eligible Fields of Study')),
                ('target_levels', models.ManyToManyField(blank=True, to='schools.educationallevel', verbose_name='Eligible Education Levels')),
            ],
            options={
                'verbose_name': 'Scholarship',
                'verbose_name_plural': 'Scholarships',
                'ordering': ['name'],
            },
        ),
    ]
