# Generated by Django 5.0.7 on 2024-11-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_motto_school_tuition_alter_school_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.ManyToManyField(blank=True, null=True, related_name='schools', to='schools.schooltype', verbose_name='type'),
        ),
    ]
