# Generated by Django 5.1.6 on 2025-02-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_fieldofstudy_alter_school_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.ManyToManyField(to='schools.schooltype', verbose_name='type'),
        ),
    ]
