# Generated by Django 5.0.7 on 2024-11-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_school_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='endowment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, verbose_name='endowment'),
        ),
    ]
