# Generated by Django 5.1.6 on 2025-05-25 11:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_founder_organization_established_year_and_more'),
        ('schools', '0004_alter_school_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Type Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_need_based', models.BooleanField(default=False, help_text='Does this require financial need?')),
                ('is_merit_based', models.BooleanField(default=False, help_text='Is this based on academic/skill merit?')),
                ('is_athletic', models.BooleanField(default=False, help_text='Is this for athletic performance?')),
                ('is_organization_specific', models.BooleanField(default=False, help_text='Linked to specific organization?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scholarship Type',
                'verbose_name_plural': 'Scholarship Types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='scholarship',
            name='destination_countries',
            field=models.ManyToManyField(related_name='destination_scholarships', to='schools.country'),
        ),
        migrations.AddField(
            model_name='school',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.scholarship')),
            ],
            options={
                'verbose_name': 'Scholarship by organization',
                'verbose_name_plural': 'Scholarship by organization',
            },
        ),
        migrations.AddField(
            model_name='scholarship',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.scholarshiptype'),
        ),
        migrations.CreateModel(
            name='SchoolScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.scholarship')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
            options={
                'verbose_name': 'Scholarship by school',
                'verbose_name_plural': 'Scholarship by schools',
            },
        ),
    ]
