# Generated by Django 5.0.7 on 2024-11-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_alter_school_endowment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='motto',
            field=models.CharField(blank=True, default='N/A', max_length=250, verbose_name='motto'),
        ),
    ]
