# Generated by Django 5.1.6 on 2025-05-25 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_scholarshiptype_scholarship_destination_countries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolCustomizeButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(default=0, help_text='Display order of the button.')),
                ('name', models.CharField(default='Untitled', help_text='Text displayed on the button.', max_length=100)),
                ('link', models.URLField(help_text='Target URL when button is clicked.')),
                ('color', models.CharField(default='#1D4ED8', help_text='Hex color for the button background.', max_length=7)),
                ('text_color', models.CharField(default='#FFFFFF', help_text='Hex color for the button text.', max_length=7)),
                ('icon', models.CharField(blank=True, help_text="Optional icon class (e.g. 'fa fa-book') or emoji.", max_length=50, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_buttons', to='schools.school')),
            ],
            options={
                'verbose_name': 'Custom School Button',
                'verbose_name_plural': 'Custom School Buttons',
                'ordering': ['order_number'],
            },
        ),
    ]
