# Generated by Django 5.2.3 on 2025-06-26 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_schoolcustomizebutton'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldofstudy',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='level',
            field=models.CharField(blank=True, choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('postgraduate', 'Postgraduate'), ('phd', 'PhD')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='fields_of_study', to='schools.school'),
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
