# Generated by Django 5.0.7 on 2024-11-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_school_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='schools', to='schools.schooltype', verbose_name='type'),
        ),
    ]
