# Generated by Django 5.2.3 on 2025-07-16 15:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_fieldofstudy_code_fieldofstudy_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='unique ID')),
                ('degree_name', models.CharField(max_length=75, unique=True, verbose_name='Level')),
                ('badge', models.CharField(blank=True, max_length=125, verbose_name='badge')),
                ('color', models.CharField(blank=True, max_length=6, verbose_name='color')),
                ('description', models.CharField(blank=True, default='No description', max_length=500, verbose_name='description')),
                ('slug', models.SlugField(max_length=75, verbose_name='slug')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='status')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
            ],
            options={
                'verbose_name': 'education level',
                'verbose_name_plural': 'education levels',
                'ordering': ('degree_name', '-created_date', 'updated_date'),
            },
        ),
        migrations.CreateModel(
            name='PhoneContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contact',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='address',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='unique identifier'),
        ),
        migrations.AddField(
            model_name='educationallevel',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='degree_levels',
            field=models.ManyToManyField(blank=True, related_name='school_education_degrees', to='schools.educationdegree', verbose_name='school eduction degree'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('local_name', models.CharField(blank=True, max_length=128)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'state',
                'verbose_name_plural': 'states',
                'ordering': ['name'],
                'unique_together': {('name', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SchoolBranchInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='name')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='street')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='city')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='zip code')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info_branch', to='schools.phonecontact')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_branch', to='schools.country')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_branch', to='schools.school')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_branch', to='schools.state')),
            ],
            options={
                'verbose_name': 'School branch',
                'verbose_name_plural': 'School branches',
                'ordering': ['name', 'created_at'],
            },
        ),
    ]
