# Generated by Django 5.0.7 on 2024-11-24 06:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_alter_school_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='unique ID')),
                ('level_name', models.CharField(max_length=75, unique=True, verbose_name='Level')),
                ('badge', models.CharField(blank=True, max_length=125, verbose_name='badge')),
                ('color', models.CharField(blank=True, max_length=6, verbose_name='color')),
                ('description', models.CharField(blank=True, default='No description', max_length=500, verbose_name='description')),
                ('slug', models.SlugField(max_length=75, verbose_name='slug')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'education level',
                'verbose_name_plural': 'education levels',
                'ordering': ('level_name', '-created_date', 'updated_date'),
            },
        ),
        migrations.AddField(
            model_name='school',
            name='platforms',
            field=models.ManyToManyField(related_name='school_platforms', through='schools.PlatformProfile', to='schools.platform', verbose_name='platforms'),
        ),
        migrations.AlterField(
            model_name='platformprofile',
            name='profile_url',
            field=models.URLField(blank=True, help_text="URL of the school's profile on the platform"),
        ),
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='school_types', to='schools.schooltype', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='school',
            name='Platform',
            field=models.ManyToManyField(blank=True, related_name='school_educational_levels', to='schools.educationallevel', verbose_name='school level'),
        ),
    ]
