# Generated by Django 5.2.3 on 2025-07-21 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_college_alter_educationallevel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationdegree',
            options={'ordering': ('degree_name', '-created_date', 'updated_date'), 'verbose_name': 'education degree', 'verbose_name_plural': 'education degrees'},
        ),
    ]
