# Generated by Django 5.0.7 on 2024-11-24 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_educationallevel_school_platforms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='Platform',
            new_name='educational_level',
        ),
    ]
