# Generated by Django 5.2.3 on 2025-07-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_alter_educationdegree_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
