# Generated by Django 5.0.7 on 2024-11-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_rename_platform_school_educational_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='educational_level',
            new_name='educational_levels',
        ),
    ]
