# Generated by Django 5.0.7 on 2024-11-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_rename_educational_level_school_educational_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='short_name',
            field=models.CharField(blank=True, max_length=5, unique=True, verbose_name='short name'),
        ),
    ]
