# Generated by Django 5.0.7 on 2024-11-24 10:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_platform_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='platform',
            name='uuid',
            field=models.URLField(default=uuid.uuid4, unique=True, verbose_name='unique identifier'),
        ),
    ]
