# Generated by Django 5.0.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
        ("schools", "0009_college_alter_educationallevel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="street_address",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="street address"
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="address_line_2",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="address line 2"
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="box_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="box number"
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="postal code"
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schools",
                to="geo.country",
                verbose_name="country",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schools",
                to="geo.state",
                verbose_name="state",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schools",
                to="geo.city",
                verbose_name="city",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="village",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schools",
                to="geo.village",
                verbose_name="village",
            ),
        ),
    ]
