# Generated by Django 5.2.3 on 2025-07-27 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_schooltype_is_deleted'),
        ('schools', '0013_add_school_address_fields'),
    ]

    operations = [
    ]
