# Generated by Django 5.0.7 on 2024-11-24 10:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_remove_platform_is_active_alter_platform_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='self_data',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='self data field'),
        ),
        migrations.AddField(
            model_name='school',
            name='self_data',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='self data field'),
        ),
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.URLField(default=uuid.uuid4, unique=True, verbose_name='unique identifier'),
        ),
    ]
