# Generated by Django 5.0.7 on 2024-11-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_platform_is_active_platform_self_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, max_length=75, verbose_name='slug'),
        ),
    ]
