# Generated by Django 5.0.7 on 2024-11-24 10:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_school_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='unique identifier'),
        ),
    ]
