# Generated by Django 5.2.3 on 2025-08-04 13:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_city_local_name_country_local_name_state_local_name_and_more'),
        ('schools', '0016_revert_to_imagefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolbranchinformation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_branch', to='geo.country'),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=None,
        ),
        migrations.AlterField(
            model_name='schoolbranchinformation',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_branch', to='geo.state'),
        ),
        migrations.AlterModelOptions(
            name='schooltype',
            options={'ordering': ['type'], 'verbose_name': 'School Type', 'verbose_name_plural': 'School Types'},
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='destination_countries',
            field=models.ManyToManyField(related_name='destination_scholarships', to='geo.country'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='target_countries',
            field=models.ManyToManyField(blank=True, to='geo.country', verbose_name='Eligible Countries'),
        ),
        migrations.CreateModel(
            name='CandidateQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='unique ID')),
                ('required_subjects', models.JSONField(blank=True, null=True, verbose_name='Required Subjects')),
                ('min_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)], verbose_name='GPA')),
                ('min_english_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Minimum English Score')),
                ('age_range', models.CharField(blank=True, help_text='e.g., 18-25, 26-30', max_length=50, verbose_name='Age Range')),
                ('qualifications', models.TextField(blank=True, verbose_name='Qualifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_qualifications', to='schools.major')),
                ('required_degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_qualifications', to='schools.educationdegree', verbose_name='Required Degree')),
            ],
            options={
                'verbose_name': 'Candidate Qualification',
                'verbose_name_plural': 'Candidate Qualifications',
                'ordering': ['created_at', 'updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='unique ID')),
                ('name', models.CharField(max_length=255, verbose_name='Document Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('accepted_formats', models.CharField(blank=True, max_length=255, verbose_name='Accepted Formats')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Is Mandatory')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='schools.major')),
            ],
            options={
                'verbose_name': 'Document Requirement',
                'verbose_name_plural': 'Document Requirements',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
