# Generated by Django 5.0.7 on 2024-11-24 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_alter_platform_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformprofile',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_profiles_platform', to='schools.platform'),
        ),
        migrations.AlterField(
            model_name='platformprofile',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_profiles_school', to='schools.school'),
        ),
    ]
