# Generated by Django 5.2.3 on 2025-08-04 14:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_city_local_name_country_local_name_state_local_name_and_more'),
        ('schools', '0017_alter_schoolbranchinformation_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolbranch',
            name='location',
            field=models.CharField(blank=True, help_text='Geographical location or coordinates', max_length=255, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='schoolbranch',
            name='village',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='geo.village'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schoolbranch',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='geo.city'),
        ),
        migrations.AlterField(
            model_name='schoolbranch',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='geo.country'),
        ),
        migrations.AlterField(
            model_name='schoolbranch',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='geo.state'),
        ),
        migrations.DeleteModel(
            name='SchoolBranchInformation',
        ),
    ]
