# Generated by Django 5.0.7 on 2024-11-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_alter_platformprofile_platform_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformprofile',
            options={'verbose_name': 'platform profile', 'verbose_name_plural': 'platform profiles'},
        ),
        migrations.RemoveConstraint(
            model_name='platformprofile',
            name='unique_school_platform',
        ),
    ]
