# Generated by Django 5.2.3 on 2025-08-04 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_city_local_name_country_local_name_state_local_name_and_more'),
        ('schools', '0018_schoolbranch_location_schoolbranch_village_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolbranch',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='geo.city'),
        ),
        migrations.AlterField(
            model_name='schoolbranch',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='geo.country'),
        ),
        migrations.AlterField(
            model_name='schoolbranch',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='geo.state'),
        ),
        migrations.AlterField(
            model_name='schoolbranch',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='geo.village'),
        ),
    ]
