# Generated by Django 5.0.7 on 2024-12-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_alter_platformprofile_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='platformprofile',
            index=models.Index(fields=['school', 'platform'], name='school_platform_idx'),
        ),
    ]
