# Generated by Django 5.2.3 on 2025-08-04 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0019_alter_schoolbranch_city_alter_schoolbranch_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolbranch',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='schools.school', verbose_name='School'),
            preserve_default=False,
        ),
    ]
