# Generated by Django 5.2.3 on 2025-08-04 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0020_schoolbranch_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolbranch',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='schools.school', verbose_name='School'),
        ),
    ]
