# Generated by Django 5.2.3 on 2025-08-05 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0021_alter_schoolbranch_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBranchContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('contact_value', models.CharField(max_length=15, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('contact_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('website', 'Website'), ('social_media', 'Social Media')], default='phone', max_length=50, verbose_name='contact type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='schools.schoolbranch', verbose_name='branch')),
            ],
            options={
                'verbose_name': 'School Branch Contact Info',
                'verbose_name_plural': 'School Branch Contact Info',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='PhoneContact',
        ),
    ]
