# Generated by Django 5.2.3 on 2025-08-05 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0023_remove_school_self_data_address_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='schoolbranch',
            name='colleges',
        ),
        migrations.AddField(
            model_name='college',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='colleges', to='schools.schoolbranch', verbose_name='Branches'),
        ),
        migrations.AddField(
            model_name='college',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_colleges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='college',
            name='degrees',
            field=models.ManyToManyField(blank=True, related_name='colleges', to='schools.educationdegree', verbose_name='Degrees'),
        ),
        migrations.AddField(
            model_name='major',
            name='degrees',
            field=models.ManyToManyField(blank=True, related_name='majors', to='schools.educationdegree', verbose_name='Degrees'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='scholarshiptype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='scholarshiptype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schoolbranch',
            name='degrees_offered',
            field=models.ManyToManyField(blank=True, related_name='school_branches', to='schools.educationdegree'),
        ),
        migrations.AlterField(
            model_name='schoolbranch',
            name='majors_offered',
            field=models.ManyToManyField(blank=True, related_name='school_branches', to='schools.major'),
        ),
        migrations.AlterField(
            model_name='schoolbranch',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_branches', to='schools.school', verbose_name='School'),
        ),
    ]
