# Generated by Django 5.2.3 on 2025-08-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0024_remove_major_degree_remove_schoolbranch_colleges_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationscholarship',
            options={'verbose_name': 'Scholarship by organization', 'verbose_name_plural': 'Scholarship by organizations'},
        ),
    ]
