# Generated by Django 5.2.7 on 2025-10-15 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0025_alter_organizationscholarship_options'),
    ]

    operations = [
    ]
