# Generated by Django 5.2.3 on 2025-07-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='local_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='country',
            name='local_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='state',
            name='local_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='village',
            name='local_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
