# Generated by Django 5.1.6 on 2025-03-09 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('user', '0003_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/', verbose_name='file')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='file name')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='content type')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
            },
        ),
        migrations.AddField(
            model_name='education',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='user.attachment', verbose_name='attachments'),
        ),
        migrations.AddField(
            model_name='experience',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='user.attachment', verbose_name='attachments'),
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'verbose_name': 'hobby',
                'verbose_name_plural': 'hobbies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(blank=True, max_length=100, verbose_name='level')),
                ('is_native', models.BooleanField(default=False, verbose_name='native')),
                ('attachments', models.ManyToManyField(blank=True, to='user.attachment', verbose_name='attachments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='position')),
                ('relationship', models.CharField(blank=True, max_length=100, verbose_name='relationship')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='email')),
                ('attachments', models.ManyToManyField(blank=True, to='user.attachment', verbose_name='attachments')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to='organization.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'verbose_name': 'reference',
                'verbose_name_plural': 'references',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(blank=True, max_length=100, verbose_name='level')),
                ('attachments', models.ManyToManyField(blank=True, to='user.attachment', verbose_name='attachments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'ordering': ['name'],
            },
        ),
    ]
