# Generated by Django 5.1.6 on 2025-05-25 11:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_scholarshiptype_scholarship_destination_countries_and_more'),
        ('user', '0004_attachment_education_attachments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_url', models.URLField(blank=True, help_text="URL of the school's profile on the platform")),
                ('username', models.CharField(blank=True, help_text='Username or handle on the platform', max_length=128)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_profiles_platform', to='schools.platform')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_profiles', to='user.profile')),
            ],
            options={
                'verbose_name': 'contact profile',
                'verbose_name_plural': 'contact profiles',
            },
        ),
    ]