# Generated by Django 5.1.6 on 2025-05-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profilecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecontact',
            name='privacy',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Connected'), (2, 'Private')], default=0),
        ),
    ]