# Generated by Django 5.1.6 on 2025-05-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profilecontact_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(default='unset', max_length=75),
        ),
    ]
