# Generated by Django 5.2.7 on 2025-10-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, 'Elementary'), (2, 'Limited Working'), (3, 'Professional Working'), (4, 'Full Professional'), (5, 'Native or Bilingual')], help_text='Language proficiency level', null=True, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], help_text='Proficiency level for this skill', null=True, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
